haru-speak/server

- be/src/main/java/com/example/be/common/CodeAndMessages.java
- be/src/main/java/com/example/be/common/config/SpeakingLogTypeUpperCaseConverter.java
- be/src/main/java/com/example/be/common/config/SwaggerConfig.java
- be/src/main/java/com/example/be/common/config/WebConfig.java
- be/src/main/java/com/example/be/common/exception/BaseException.java
- be/src/main/java/com/example/be/common/exception/ErrorCodeAndMessages.java
- be/src/main/java/com/example/be/common/exception/GlobalExceptionHandler.java
- be/src/main/java/com/example/be/common/exception/speakinglog/InvalidSpeakingLogTypeException.java
- be/src/main/java/com/example/be/common/response/BaseResponse.java
- be/src/main/java/com/example/be/common/response/ResponseCodeAndMessages.java
- be/src/main/java/com/example/be/core/application/QuestionService.java
- be/src/main/java/com/example/be/core/application/SpeakingLogService.java
- be/src/main/java/com/example/be/core/application/dto/request/SpeakingLogModifyRequest.java
- be/src/main/java/com/example/be/core/application/dto/request/SpeakingLogRequest.java
- be/src/main/java/com/example/be/core/application/dto/response/CommentResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/QuestionResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/SpeakingLogDetailResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/SpeakingLogResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/SpeakingLogsResponse.java
- be/src/main/java/com/example/be/core/domain/SpeakingLogType.java
- be/src/main/java/com/example/be/core/web/QuestionController.java
- be/src/main/java/com/example/be/core/web/SpeakingLogController.java
- be/src/test/java/com/example/be/core/web/SpeakingLogControllerFindByTypeTest.java
- be/src/test/java/com/example/be/core/web/SpeakingLogControllerTest.java
Closes #4
<br><br>
- 목업 API 팀원들과 함께 만들어보기 
- Request DTO, Response DTO, Controller에 대해서만 작성 
- 예시 컨트롤러 테스트 추가
<br><br>
- API 문서의 세부 명세(필드, 값 범위 제한 등)가 아직 작성되지 않았습니다. 추후 작업에서 개선하려 합니다.
- 컨트롤러 테스트의 경우 멤버들이 각자 맡아서 진행하려고 합니다.
<br><br>
- Swagger API 
- SpeakingLogControllerFindByTypeTest
> 목업 API 함께 만들어보기 및 예시 컨트롤러 테스트 추가

- be/docker/Dockerfile
Closes #8 
<br><br>
- Dockerfile 작성
> deploy: [#8] Dockerfile 작성

- be/src/main/java/com/example/be/core/application/dto/response/SpeakingLogDetailResponse.java
- be/src/main/java/com/example/be/core/web/SpeakingLogController.java
- be/src/test/java/com/example/be/core/web/speakinglog/SpeakingLogControllerDetailFindTest.java
- be/src/test/java/com/example/be/core/web/speakinglog/SpeakingLogControllerFindByTypeTest.java
Related to #24 
<br><br>
- SpeakingLogController 상세 조회 테스트 완료
- API URL을 `api.haru-speak.site/~` 로 변경하기로 하였으므로, `~/api`로 시작하는 URL 모두 수정 및 관련 ControllerTest 수정
> SpeakingLogController 상세 조회 테스트 완료

- be/src/test/java/com/example/be/core/web/speakinglog/SpeakingLogControllerDeleteTest.java
Related to #24 
- spakingLogController 삭제 테스트 완료
> SpeakingLogController 삭제 테스트 완료

- be/src/test/java/com/example/be/core/web/speakinglog/SpeakingLogControllerCreateTest.java
Related to #24 
<br><br>
- SpeakingLogController 생성 테스트 완료
> SpeakingLogController 생성 테스트 완료

- be/build.gradle
- be/src/main/java/com/example/be/common/config/SecurityConfig.java
- be/src/main/java/com/example/be/core/application/dto/request/MemberFormRequest.java
- be/src/main/java/com/example/be/core/domain/Member.java
Closes #6
<br><br>
- 회원정보를 저장하는 Member Entity 생성 (필드는 로그인 로직에 필요한 것만 일단 생성된 상태)
- 회원가입 화면으로부터 넘어오는 가입정보를 담을 DTO 생성 (=MemberFormRequest)
- Spring Security 의존성 추가 및 회원가입&로그인&로그아웃 처리에 필요한 SecurityConfig 설정
<br><br>
- Member Entity와 DTO에 대해서 수정이 필요한 부분 지적해주시면 감사드리겠습니다
<br><br>
> SecurityConfig 설정 및 회원가입 DTO와 Member 도메인 생성

- be/src/main/java/com/example/be/core/application/SpeakingLogService.java
- be/src/main/java/com/example/be/core/domain/speakinglog/SpeakingLog.java
- be/src/test/java/com/example/be/core/application/speakinglog/SpeakingLogModifyTest.java
Closes #35 
<br><br>
- 스피킹 로그 수정 기능 구현
- 스피킹 로그 수정 관련 테스트 코드 작성
- 성공시 테스트 코드 작성
- 잘못된 스피킹 로그 아이디가 들어왔을 때 실패시 테스트 코드 작성
<br>
> SpeakingLog 수정 기능 구현 및 관련 테스트 코드 작성

- be/src/main/java/com/example/be/common/exception/ErrorCodeAndMessages.java
- be/src/main/java/com/example/be/common/exception/GlobalExceptionHandler.java
- be/src/main/java/com/example/be/common/response/BaseResponse.java
- be/src/main/java/com/example/be/core/application/SpeakingLogService.java
- be/src/main/java/com/example/be/core/application/dto/request/SpeakingLogConditionRequest.java
- be/src/main/java/com/example/be/core/application/dto/request/SpeakingLogModifyRequest.java
- be/src/main/java/com/example/be/core/application/dto/request/SpeakingLogRequest.java
- be/src/main/java/com/example/be/core/application/dto/response/CommentResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/QuestionResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/SpeakingLogDetailResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/SpeakingLogResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/SpeakingLogsResponse.java
- be/src/main/java/com/example/be/core/web/SpeakingLogController.java
- be/src/test/java/com/example/be/core/application/speakinglog/SpeakingLogDetailFindTest.java
- be/src/test/java/com/example/be/core/application/speakinglog/SpeakingLogFindAllTest.java
- be/src/test/java/com/example/be/core/tool/DataBaseConfigurator.java
- be/src/test/java/com/example/be/core/web/speakinglog/SpeakingLogControllerCreateTest.java
- be/src/test/java/com/example/be/core/web/speakinglog/SpeakingLogControllerFindByTypeTest.java
- be/src/test/java/com/example/be/core/web/speakinglog/SpeakingLogControllerModifyTest.java
- be/src/test/resources/application.yml
Closes #46
<br><br>
- SpeakingLog와 관련된 Controller에서 받는 모든 파라미터(Path Variable, Request Body 등)에 대해 Bean Validation 적용
<br><br>
- 이번 PR로 인해 좀 더 타이트한 검증과 예외처리가 가능해졌습니다!
> SpeakingLog에 Bean Validation 적용하기

- be/src/main/java/com/example/be/common/exception/ErrorCodeAndMessages.java
- be/src/main/java/com/example/be/common/exception/study/InvalidStudyTypeException.java
- be/src/main/java/com/example/be/common/response/ResponseCodeAndMessages.java
- be/src/main/java/com/example/be/core/application/StudyService.java
- be/src/main/java/com/example/be/core/application/dto/request/StudyRequest.java
- be/src/main/java/com/example/be/core/application/dto/response/StudiesResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/StudyDetailResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/StudyResponse.java
- be/src/main/java/com/example/be/core/domain/study/StudyType.java
- be/src/main/java/com/example/be/core/web/StudyController.java
Closes #43
- 스터디 관련 응답 코드 작성
- 임시 서비스 클래스 추가
- CRUD 컨트롤러 작성
- 목업 API 작성
아직 검색과 좋아요, 찜, 댓글 기능에 대한 컨트롤러는 작성하지 않았습니다. 
피그마 화면, erd, api 명세서를 보시고 각 기능과 컨트롤러, DTO가 일치하는지 확인해주시면 감사하겠습니다!! 
- 피그마(https://www.figma.com/file/FPIahJATLiZudwTdJnnGBO/%ED%95%98%EB%A3%A8%EC%8A%A4%ED%94%BD-(Team)?node-id=0%3A1)
- erd (https://www.erdcloud.com/d/MKSD3XnMafMQHPxk9)
- API 노션 (https://www.notion.so/API-c6195e5c6b2c44cfa9952f394182b8ff)
> 스터디 관련 컨트롤러 및 목업 API 작성

- be/src/main/java/com/example/be/common/response/ResponseCodeAndMessages.java
- be/src/main/java/com/example/be/core/application/AssignmentService.java
- be/src/main/java/com/example/be/core/application/dto/request/AssignmentRequest.java
- be/src/main/java/com/example/be/core/application/dto/request/AssignmentSubmitRequest.java
- be/src/main/java/com/example/be/core/application/dto/response/AssignmentDetailResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/AssignmentResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/AssignmentsResponse.java
- be/src/main/java/com/example/be/core/web/AssignmentController.java
Closes #44 
- 과제 관련 응답 코드 작성
- 임시 서비스 클래스 추가
- CRUD 컨트롤러 작성
- 목업 API 작성
피그마 화면, erd, api 명세서를 보시고 각 기능과 컨트롤러, DTO가 일치하는지 확인해주시면 감사하겠습니다!! 
- 피그마(https://www.figma.com/file/FPIahJATLiZudwTdJnnGBO/%ED%95%98%EB%A3%A8%EC%8A%A4%ED%94%BD-(Team)?node-id=0%3A1)
- erd (https://www.erdcloud.com/d/MKSD3XnMafMQHPxk9)
- API 노션 (https://www.notion.so/API-c6195e5c6b2c44cfa9952f394182b8ff)
> 과제 관련 컨트롤러 및 목업 API 작성

- be/src/main/java/com/example/be/common/response/ResponseCodeAndMessages.java
- be/src/main/java/com/example/be/core/application/AssignmentService.java
- be/src/main/java/com/example/be/core/application/dto/request/AssignmentRequest.java
- be/src/main/java/com/example/be/core/application/dto/request/AssignmentSubmitRequest.java
- be/src/main/java/com/example/be/core/application/dto/response/AssignmentDetailResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/AssignmentResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/AssignmentsResponse.java
- be/src/main/java/com/example/be/core/web/AssignmentController.java
[Reverts haru-speak/server#52]
Closes #44 
- 과제 관련 응답 코드 작성
- 임시 서비스 클래스 추가
- CRUD 컨트롤러 작성
- 목업 API 작성
피그마 화면, erd, api 명세서를 보시고 각 기능과 컨트롤러, DTO가 일치하는지 확인해주시면 감사하겠습니다!! 
- 피그마(https://www.figma.com/file/FPIahJATLiZudwTdJnnGBO/%ED%95%98%EB%A3%A8%EC%8A%A4%ED%94%BD-(Team)?node-id=0%3A1)
- erd (https://www.erdcloud.com/d/MKSD3XnMafMQHPxk9)
- API 노션 (https://www.notion.so/API-c6195e5c6b2c44cfa9952f394182b8ff)
> [RE] "Revert "과제 관련 컨트롤러 및 목업 API 작성""

- be/src/main/java/com/example/be/common/response/ResponseCodeAndMessages.java
- be/src/main/java/com/example/be/core/application/StudyService.java
- be/src/main/java/com/example/be/core/application/dto/request/StudyConditionRequest.java
- be/src/main/java/com/example/be/core/application/dto/request/StudyRequest.java
- be/src/main/java/com/example/be/core/application/dto/response/StudyDetailResponse.java
- be/src/main/java/com/example/be/core/web/StudyController.java
- be/src/test/java/com/example/be/core/web/study/InitStudyControllerTest.java
- be/src/test/java/com/example/be/core/web/study/StudyControllerCreatTest.java
- be/src/test/java/com/example/be/core/web/study/StudyControllerDeleteTest.java
- be/src/test/java/com/example/be/core/web/study/StudyControllerDetailFindTest.java
- be/src/test/java/com/example/be/core/web/study/StudyControllerFindByTypeTest.java
- be/src/test/java/com/example/be/core/web/study/StudyControllerModifyTest.java
Closes #55
<br><br>
- 스터디 생성 컨트롤러
- 스터디 타입 별 전체 조회 컨트롤러
- 스터디 상세 조회 컨트롤러
- 스터디 수정 컨트롤러
- 스터디 삭제 컨트롤러
<br><br>
기존 코드에 스터디의 각 타입 별 조회에 필요한 DTO를 추가했습니다. 
그에 따라 controller와 service 코드의 파라미터가 바뀌었으니 확인해주시면 감사하겠습니다!
> 스터디 CRUD 관련 컨트롤러 테스트 작성

- be/src/main/java/com/example/be/core/domain/assignment/Assignment.java
- be/src/main/java/com/example/be/core/domain/assignment/AssignmentMember.java
- be/src/main/java/com/example/be/core/domain/study/Study.java
- be/src/main/java/com/example/be/core/domain/study/StudyComment.java
- be/src/main/java/com/example/be/core/domain/study/StudyFavorite.java
- be/src/main/java/com/example/be/core/domain/study/StudyInterest.java
- be/src/main/java/com/example/be/core/domain/study/StudyMember.java
Closes #59 
<br>
- Assignment Entity 작성
- AssignmentMember Entity 작성
- Study Entity 작성
- StudyComment Entity 작성
- StudyFavorite Entity 작성
- StudyInterest Entity 작성
- StudyMember Entity 작성
> Study, Assignment 관련 Entity 작성

- be/src/main/java/com/example/be/core/application/StudyService.java
- be/src/main/java/com/example/be/core/repository/study/StudyMemberRepository.java
- be/src/test/java/com/example/be/core/application/study/StudyCreateTest.java
Closes #62 
<br><br>
- 스터디 생성 서비스 로직 작성
- 스터디 생성 서비스 테스트 코드 작성
> 스터디 생성 서비스 로직 및 관련 테스트 코드 작성

- be/src/main/java/com/example/be/core/application/StudyService.java
- be/src/main/java/com/example/be/core/repository/study/StudyCommentRepository.java
- be/src/main/java/com/example/be/core/repository/study/StudyFavoriteRepository.java
- be/src/test/java/com/example/be/core/application/study/StudyFindAllTest.java
- be/src/test/java/com/example/be/core/tool/DataBaseConfigurator.java
> Study 전체 조회 관련 서비스 로직 및 테스트 작성

- be/src/main/java/com/example/be/common/exception/ErrorCodeAndMessages.java
- be/src/main/java/com/example/be/common/exception/study/NotFoundStudyIdException.java
- be/src/main/java/com/example/be/core/application/StudyService.java
- be/src/main/java/com/example/be/core/application/dto/response/StudyCommentResponse.java
- be/src/main/java/com/example/be/core/application/dto/response/StudyDetailResponse.java
- be/src/main/java/com/example/be/core/repository/study/StudyCommentRepository.java
- be/src/test/java/com/example/be/core/application/study/StudyFindDetailTest.java
Closes #66 
<br><br>
- 스터디 상세 조회 서비스 로직 작성
- 스터디 상세 조회 서비스 테스트 코드 작성
> 스터디 상제 조회 서비스 로직 및 관련 테스트 코드 작성

- be/src/main/java/com/example/be/core/application/StudyService.java
- be/src/main/java/com/example/be/core/domain/study/Study.java
- be/src/main/java/com/example/be/core/repository/study/StudyCommentRepository.java
- be/src/main/java/com/example/be/core/repository/study/StudyFavoriteRepository.java
- be/src/test/java/com/example/be/core/application/study/StudyDeleteTest.java
- be/src/test/java/com/example/be/core/application/study/StudyModifyTest.java
Closes #68 
<br><br>
- 스터디 수정 서비스  로직 작성
- 스터디 수정 테스트 코드 작성
- 스터디 삭제 서비스  로직 작성
- 스터디 삭제 테스트 코드 작성
<br><br>
스터디 수정 테스트
스터디 삭제 테스트
> 스터디 수정, 삭제 관련 서비스 로직 및 테스트 작성

- be/src/main/java/com/example/be/core/application/AssignmentService.java
- be/src/main/java/com/example/be/core/application/dto/response/AssignmentResponse.java
- be/src/main/java/com/example/be/core/repository/assignment/AssignmentMemberRepository.java
- be/src/main/java/com/example/be/core/repository/study/StudyMemberRepository.java
- be/src/test/java/com/example/be/core/application/assignment/AssignmentFindAllTest.java
- be/src/test/java/com/example/be/core/application/study/StudyCreateTest.java
- be/src/test/java/com/example/be/core/tool/DataBaseConfigurator.java
Closes #70 
<br><br>
- 과제 전체 조회 서비스 로직 작성
- 과제 전체 조회 테스트 코드 작성
> 과제 전체 조회 서비스 로직 및 테스트 코드 작성

- be/src/main/java/com/example/be/common/exception/ErrorCodeAndMessages.java
- be/src/main/java/com/example/be/common/exception/assignment/NotFoundAssignmentIdException.java
- be/src/main/java/com/example/be/core/application/AssignmentService.java
- be/src/main/java/com/example/be/core/domain/assignment/Assignment.java
- be/src/test/java/com/example/be/core/application/assignment/AssignmentModifyTest.java
Closes #74 
<br><br>
- 과제 수정 서비스 로직 작성
- 과제 수정 테스트 코드 작성
> 과제 수정 서비스 로직 및 테스트 작성

- be/src/main/java/com/example/be/common/exception/ErrorCodeAndMessages.java
- be/src/main/java/com/example/be/common/exception/assignment/NotFoundAssignmentIdException.java
- be/src/main/java/com/example/be/core/application/AssignmentService.java
- be/src/test/java/com/example/be/core/application/assignment/AssignmentDeleteTest.java
Closes #72 
<br><br>
- 과제 삭제 서비스 로직 작성
- 과제 삭제 테스트 코드 작성
> 과제 삭제 서비스 로직 및 테스트 코드 작성

- be/src/main/java/com/example/be/core/domain/goal/Goal.java
- be/src/main/java/com/example/be/core/domain/goal/GoalMember.java
Closes #83 
<br><br>
- Goal, GoalMember Entity 작성
```sql
SET AUTOCOMMIT = 0;
-- member
INSERT INTO member(created_at, deleted, updated_at, email, nickname, profile_image, unique_id)
VALUES ('2023-01-30 00:00:01', false, '2023-01-30 00:00:01', null, "멤버1", "https://haru-speak-s3.s3.ap-northeast-2.amazonaws.com/image/b61ff148-cab3-493e-ada6-5e46c7e0f7ec.jpeg",  1);
INSERT INTO member(created_at, deleted, updated_at, email, nickname, profile_image, unique_id)
VALUES ('2023-01-30 00:00:01', false, '2023-01-30 00:00:01', "haru-speak1@gmail.com", "멤버2", "https://haru-speak-s3.s3.ap-northeast-2.amazonaws.com/image/b61ff148-cab3-493e-ada6-5e46c7e0f7ec.jpeg",  2);
INSERT INTO member(created_at, deleted, updated_at, email, nickname, profile_image, unique_id)
VALUES ('2023-01-30 00:00:01', false, …
```
> Goal, GoalMember Entity 작성

- be/src/main/java/com/example/be/common/exception/ErrorCodeAndMessages.java
- be/src/main/java/com/example/be/common/exception/member/InvalidSpeakingTestTypeException.java
- be/src/main/java/com/example/be/common/exception/member/NotFoundFollowRelationshipException.java
- be/src/main/java/com/example/be/common/exception/member/NotFoundMemberIdException.java
- be/src/main/java/com/example/be/common/exception/member/grade/InvalidSizeSpeakingGradeException.java
- be/src/main/java/com/example/be/common/response/ResponseCodeAndMessages.java
- be/src/main/java/com/example/be/core/application/MemberService.java
- be/src/main/java/com/example/be/core/application/dto/response/FollowResponse.java
- be/src/main/java/com/example/be/core/domain/member/Follow.java
- be/src/main/java/com/example/be/core/domain/member/SpeakingTestType.java
- be/src/main/java/com/example/be/core/repository/member/FollowRepository.java
- be/src/main/java/com/example/be/core/web/MemberController.java
- be/src/test/java/com/example/be/core/application/member/MemberFollowTest.java
- be/src/test/java/com/example/be/core/web/member/MemberControllerFollowTest.java
Closes #91 
<br><br>
- 멤버 Follow 요청 기능 구현
- 멤버 Follow 취소 기능 구현
- 각각 컨트롤러 및 서비스 테스트 완료
<br><br>
> 멤버 Follow 요청 및 취소 기능 구현

- be/src/main/java/com/example/be/common/response/ResponseCodeAndMessages.java
- be/src/main/java/com/example/be/core/application/dto/response/SubjectResponse.java
- be/src/main/java/com/example/be/core/application/member/GoalService.java
- be/src/main/java/com/example/be/core/application/member/MemberService.java
- be/src/main/java/com/example/be/core/application/member/SubjectService.java
- be/src/main/java/com/example/be/core/domain/member/subject/Subject.java
- be/src/main/java/com/example/be/core/web/member/GoalController.java
- be/src/main/java/com/example/be/core/web/member/MemberController.java
- be/src/main/java/com/example/be/core/web/member/SubjectController.java
- be/src/main/java/com/example/be/oauth/provider/LoginService.java
- be/src/test/java/com/example/be/core/application/goal_subject/GoalFindAllTest.java
- be/src/test/java/com/example/be/core/application/goal_subject/SubjectFindAllTest.java
- be/src/test/java/com/example/be/core/application/member/MemberFollowTest.java
- be/src/test/java/com/example/be/core/application/member/MemberModifyTest.java
- be/src/test/java/com/example/be/core/application/member/MemberMyPageTest.java
- be/src/test/java/com/example/be/core/application/member/MemberSignUpTest.java
- be/src/test/java/com/example/be/core/web/goal_subject/GoalControllerFindAllTest.java
- be/src/test/java/com/example/be/core/web/goal_subject/SubjectControllerFindAllTest.java
- be/src/test/java/com/example/be/core/web/member/MemberControllerFollowTest.java
- be/src/test/java/com/example/be/core/web/member/MemberControllerModifyTest.java
- be/src/test/java/com/example/be/core/web/member/MemberControllerMyPageTest.java
- be/src/test/java/com/example/be/core/web/member/MemberControllerSignUpTest.java
- be/src/test/java/com/example/be/tool/DataBaseConfigurator.java
Closes #101
<br><br>
- 목표 및 주제 전체 조회 기능 구현
- 목표 및 주제 전체 조회 기능 컨트롤러 및 서비스 테스트
<br><br>
> 목표 및 주제 전체 조회 기능 구현 및 테스트 완료

- be/src/main/java/com/example/be/core/application/SpeakingLogService.java
- be/src/main/java/com/example/be/core/domain/member/Member.java
- be/src/main/java/com/example/be/core/repository/member/FollowRepository.java
- be/src/main/resources/db/default-data.sql
Closes #99
<br><br>
- Type에 따른 SpeakingLog 조회 기능 개선
<br><br>
- 리팩토링 결과가 썩 마음에 들지는 않습니다. 중복되는 코드가 여럿 보이는데 아직은 더 줄일 수 있는 방법을 찾지 못하였습니다.
추후 기본 기능 구현이 모두 완료되면, 다시 진행해보려고 합니다.
<br><br>
> Type에 따른 SpeakingLog 조회 기능 개선
